# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField()),
                ('precision', models.PositiveSmallIntegerField(choices=[(6, 'millenium'), (7, 'century'), (8, 'decade'), (9, 'year'), (10, 'month'), (11, 'day'), (12, 'hour'), (13, 'minute'), (14, 'second')])),
                ('before', models.PositiveIntegerField(blank=True, null=True)),
                ('after', models.PositiveIntegerField(blank=True, null=True)),
                ('statement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_value', to='knowledgebase.Statement')),
            ],
        ),
    ]
