# Generated by Django 2.0.2 on 2018-02-28 21:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0003_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinateValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('precision_m', models.FloatField(default=0)),
                ('height_m', models.FloatField(blank=True, default=None, null=True)),
                ('globe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordinates', to='knowledgebase.Concept')),
                ('statement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinate_value', to='knowledgebase.Statement')),
            ],
        ),
    ]
