# Generated by Django 2.0.3 on 2018-10-10 21:59

from django.db import migrations, models
import django.db.models.deletion


def fill_m2m_references(apps, schema_editor):
    Reference = apps.get_model('knowledgebase', 'Reference')

    references_to_keep = {}
    references_to_delete = set()

    for reference in Reference.objects.all():
        existing_reference = references_to_keep.get(reference.url)
        if existing_reference:
            existing_reference.statements.add(reference.statement)
            references_to_delete.add(reference.id)
        else:
            reference.statements.add(reference.statement)
            references_to_keep[reference.url] = reference

    Reference.objects.filter(id__in=references_to_delete).delete()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0004_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='statements',
            field=models.ManyToManyField(related_name='references', to='knowledgebase.Statement'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgebase.Statement'),
        ),
        migrations.RunPython(
            fill_m2m_references,
            do_nothing,
        ),
        migrations.RemoveField(
            model_name='reference',
            name='statement',
        ),
        migrations.AlterField(
            model_name='reference',
            name='url',
            field=models.URLField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
